stack: python 3.9

branches:
  only:
    - master

image:
  - Ubuntu2004
  
environment:
  GITHUB_API_KEY:
    secure: pPw+Bpz1oJbhH5UZ3M2DgmGZnXyI9zEBJqQZqTVNwmFdkfZtoRsnBPRa3s8LElGL

install:
  - cd $APPVEYOR_BUILD_FOLDER
  
  # Configure CI bot git email/username
  - git config --global user.name "AppVeyor CI Bot"
  - git config --global user.email "appveyor@appveyor.org"
  
  # Install the Twitter bot library dependencies
  - python -m pip install --upgrade pip
  - python -m pip install pillow
  - python -m pip install tweepy
  
  # Get the project submodule
  - git submodule update --init --recursive
  - git submodule update --remote --merge

  # Push the latest versions of the submodules to the repository
  - |
    if [[ `git status --porcelain` ]]; then
      git checkout master
      git add geometrize-twitter-bot
      git commit --message "Build bot updating submodule and rebuilding documentation"
      git remote rm origin
      git remote add origin https://${GITHUB_API_KEY}@github.com/Tw1ddle/geometrize-twitter-bot-docs.git > /dev/null 2>&1
      git push origin master
    fi

# Build the documentation
build_script:
  - cd $APPVEYOR_BUILD_FOLDER
  
  - pushd doxygen
  - doxygen doxygen_config
  - popd

# Deploy the documentation to the GitHub pages branch
deploy_script:
  - cd $APPVEYOR_BUILD_FOLDER

  - ls

  - mkdir gh-pages
  - pushd gh-pages

  - git clone -b gh-pages "https://${GITHUB_API_KEY}@github.com/Tw1ddle/geometrize-twitter-bot-docs.git" gh-pages
  
  - ls

  #- robocopy ..\html . /E /J /MIR /MT /NFL /XD .git 2>&1
  #- git add --all .
  #- if ($LASTEXITCODE -ne 0) { throw "git add failed: $LASTEXITCODE" }

  - touch CNAME
  - echo "botdocs.geometrize.co.uk" > CNAME

  # Note that when there is nothing to commit, git commit exits with 1.
  - git commit -m "CI bot updating documentation"
  - git push origin gh-pages 2>&1 | out-null