stack: python 3.9

branches:
  only:
    - master

image:
  - Ubuntu2004
  
environment:
  GITHUB_API_KEY:
    secure: pPw+Bpz1oJbhH5UZ3M2DgmGZnXyI9zEBJqQZqTVNwmFdkfZtoRsnBPRa3s8LElGL

install:
  - cd $APPVEYOR_BUILD_FOLDER
  
  # Configure CI bot git email/username
  - git config --global user.name "AppVeyor CI Bot"
  - git config --global user.email "appveyor@appveyor.org"
  
  # Install the Twitter bot library dependencies
  - python -m pip install --upgrade pip
  - python -m pip install pillow
  - python -m pip install tweepy
  
  # Get the project submodule
  - git submodule update --init --recursive
  - git submodule update --remote --merge

  # Push the latest versions of the submodules to the repository
  - |
    if [[ `git status --porcelain` ]]; then
      git checkout master
      git add geometrize-twitter-bot
      git commit --message "Build bot updating submodule"
      git remote rm origin
      git remote add origin https://${GITHUB_API_KEY}@github.com/Tw1ddle/geometrize-twitter-bot-docs.git > /dev/null 2>&1
      git push origin master
    fi

# Build the documentation
build_script:
  - cd $APPVEYOR_BUILD_FOLDER
  
  - pushd doxygen
  - doxygen doxygen_config
  - popd

# Deploy the documentation to the GitHub pages branch
deploy_script:
  # Important - get out of the original build folder to avoid accidentally trashing it
  - cd $APPVEYOR_BUILD_FOLDER
  - cd ..

  - ls

  - mkdir gh-pages
  - pushd gh-pages

  # Get the gh-pages branch as a separate repo
  - git clone -b gh-pages "https://${GITHUB_API_KEY}@github.com/Tw1ddle/geometrize-twitter-bot-docs.git"
  
  # Reset the gh-pages branch to empty, history and all
  - git hash-object -t tree /dev/null
  - git commit-tree -m "Empty commit" 4b825dc642cb6eb9a060e54bf8d69288fbee4904
  - git reset --hard a5c0737b92e5e5d4502e15b93d7a46d1e17b2b22
  
  # Move the newly-generated docs to the pages folder
  - cd $APPVEYOR_BUILD_FOLDER/docs
  - (shopt -s dotglob && mv * ../gh-pages)
  - cd ../gh-pages

  # Specify the domain
  - touch CNAME
  - echo "botdocs.geometrize.co.uk" > CNAME

  # Note that when there is nothing to commit, git commit exits with 1.
  - git add -A
  - git commit -m "Build bot updating documentation"
  - git push -f origin gh-pages