branches:
  only:
    - master

image:
  - Ubuntu2004
  
#environment:
#  access_token:
#    secure: TODO

install:
  - cd $APPVEYOR_BUILD_FOLDER
  # Get the Twitter bot library dependencies
  - python -m pip install pillow
  - python -m pip install tweepy
  # Get the project submodules
  - chmod +x ./update_submodule.sh
  - ./update_submodule.sh

# Build the documentation
build_script:
  - cd $APPVEYOR_BUILD_FOLDER
  - pushd doxygen
  - doxygen doxygen_config
  - popd

# Deploy artifacts
#deploy:
#  provider: S3
#  access_key_id: $(AWS_ACCESS_KEY_ID)
#  secret_access_key: $(AWS_SECRET_ACCESS_KEY)
#  bucket: $(AWS_S3_BUCKET_NAME)
#  region: us-east-1
#  unzip: false
#  set_public: true
#  folder: windows/%COMPILER_NAME%
  
# Deploy the generated documentation to GitHub Pages
#deploy:
#  provider: pages
#  skip_cleanup: true
#  local_dir: $TRAVIS_BUILD_DIR/docs/
#  github_token: $GITHUB_API_KEY
  # Sets the CNAME file for the custom domain (not enough to just set it on the Github page settings)
#  fqdn: botdocs.geometrize.co.uk
#  on:
#    branch: master